sudo: required
services:
    - docker

before_install:
    - docker build -t rajgandhi0011/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run rajgandhi0011/react-test npm test -- --coverage

after_success:
    - docker build -t rajgandhi0011/multi-client ./client
    - docker build -t rajgandhi0011/multi-nginx ./nginx
    - docker build -t rajgandhi0011/multi-server ./server
    - docker build -t rajgandhi0011/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push rajgandhi0011/multi-client
    - docker push rajgandhi0011/multi-nginx
    - docker push rajgandhi0011/multi-server
    - docker push rajgandhi0011/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-1-658747912130
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY